[package]
name = "four-in-a-row"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.4"
rulinalg = "0.4.2"
strum = "0.24.1"
strum_macros = "0.24.3"